spring.application.name=DOSW_TALLER-2
spring.data.mongodb.uri=mongodb+srv://carlos:1001204106@Cluster0.4kaejj7.mongodb.net/fintech?retryWrites=true&w=majority&appName=Cluster0&authSource=admin
spring.data.mongodb.database=fintech